/**
 * Download helper + complete track package (zip via fflate).
 */

import { zipSync, strToU8 } from "fflate";
import { serializeProject } from "./json";
import { trackToSvg } from "./svg";
import { trackToCsv } from "./csv";
import { trackToGeoJSON } from "./geojson";
import { trackToDxf } from "./dxf";
import { trackToLandXML } from "./landxml";
import { trackToObj, trackMtl } from "./obj";
import { trackToBlenderScript } from "./blender";
import { trackToOpenDrive } from "./opendrive";
import { trackToGlb } from "./glb";
import type { TerrainSurface } from "../core/terrain";
import type { Track } from "../core/types";

export function downloadFile(name: string, content: string | Uint8Array | ArrayBuffer, mime = "text/plain"): void {
  const data =
    typeof content === "string"
      ? content
      : content instanceof ArrayBuffer
        ? new Uint8Array(content)
        : content;
  const blob = new Blob([data as BlobPart], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export interface PackageOptions {
  terrain?: TerrainSurface | null;
  world?: import("../core/world/types").WorldPlan | null;
  includeGlb?: boolean;
}

/** Build the complete export package as a zip archive. */
export async function buildTrackPackage(
  track: Track,
  opts: PackageOptions = {},
): Promise<Uint8Array> {
  const base = `track-seed${track.seed}`;
  const files: Record<string, Uint8Array> = {};
  files[`${base}.track.json`] = strToU8(serializeProject(track));
  files[`${base}.svg`] = strToU8(trackToSvg(track, { drawSectors: true }));
  files[`${base}.csv`] = strToU8(trackToCsv(track));
  files[`${base}.geojson`] = strToU8(trackToGeoJSON(track));
  files[`${base}.dxf`] = strToU8(trackToDxf(track));
  files[`${base}.landxml`] = strToU8(trackToLandXML(track, { terrain: opts.terrain }));
  files[`${base}.obj`] = strToU8(trackToObj(track, { terrain: opts.terrain, world: opts.world }));
  files[`track.mtl`] = strToU8(trackMtl());
  files[`${base}.xodr`] = strToU8(trackToOpenDrive(track));
  files[`${base}_blender.py`] = strToU8(trackToBlenderScript(track, { terrain: opts.terrain, world: opts.world }));
  files["README.txt"] = strToU8(packageReadme(track));
  if (opts.includeGlb !== false) {
    try {
      const glb = await trackToGlb(track, opts.terrain, opts.world);
      files[`${base}.glb`] = new Uint8Array(glb);
    } catch (e) {
      console.warn("GLB export failed in package build", e);
    }
  }
  return zipSync(files, { level: 6 });
}

function packageReadme(track: Track): string {
  return `GRANDPRIX-GEN TRACK PACKAGE
===========================

Seed:      ${track.seed}
Length:    ${(track.length / 1000).toFixed(3)} km
Corners:   ${track.corners.length}
Version:   generator v${track.version}
Site:      ${track.site ? `${track.site.lat.toFixed(5)}, ${track.site.lon.toFixed(5)}` : "blank canvas"}

FILES
-----
.track.json   lossless native project (reopen in grandprix-gen)
.svg          top-down circuit drawing
.csv          sampled engineering data (s, x, y, z, curvature, grade, banking, speed)
.geojson      georeferenced centerline/band/sectors/corners (GIS)
.dxf          CAD drawing, 3D polylines on named layers, metric
.landxml      civil engineering exchange (alignment + profile + terrain TIN)
.obj/.mtl     generic 3D mesh (asphalt/curbs/runoff${track.terrain ? "/terrain" : ""})
.glb          glTF binary scene for Blender/engines
.xodr         ASAM OpenDRIVE road description (simulation)
_blender.py   Blender script: rebuilds editable circuit objects

Coordinates are local engineering meters (x east, y north, z up) unless
georeferenced (GeoJSON: WGS84 lon/lat). The DXF header declares meters.
Generated by grandprix-gen -- procedural circuit design sandbox.
`;
}
